apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wireguard
  template:
    metadata:
      labels:
        app: wireguard
    spec:
      containers:
        - name: wireguard
          image: ghcr.io/wfg/wireguard:latest
          securityContext:
            privileged: true
          env:
            - name: ENABLE_HTTP_PROXY
              value: "true"
            - name: HTTP_PROXY_PORT
              value: "3128"
            - name: LOG_LEVEL
              value: "info"
            - name: ALLOWED_SUBNETS
              value: "10.0.0.0/8"
            - name: WG_ALLOWED_IPS
              value: "10.2.0.0/24, 10.0.0.0/8"
          volumeMounts:
            - name: wireguard-vpn-config
              mountPath: /etc/wireguard
          ports:
            - containerPort: 3128
              name: proxy
      volumes:
        - name: wireguard-vpn-config
          secret:
            secretName: wireguard-vpn-config-secret
