name: infra-network
description: Network infrastructure setup for homelab
version: 0.1.0
apiVersion: v2
type: application
appVersion: "1.0.0"
maintainers:
  - name: KarafrOrg
    email: karafra@karafra.net
keywords:
  - networking
  - cert-manager
  - homelab
dependencies:
  - name: cert-manager
    version: v1.19.0
    repository: https://charts.jetstack.io
    import-values:
      - values-certmanager.yaml
