apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: public-ingress-gateway-certificate
spec:
  secretName: public-ingress-gateway-tls
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  dnsNames:
    - '*.karafra.net'
    - karafra.net
