apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: public-ingress-gateway
spec:
  gatewayClassName: istio
  listeners:
    - name: https
      port: 443
      protocol: HTTPS
      hostname: 'grafana.karafra.net'
      tls:
        mode: Terminate
        certificateRefs:
          - group: ''
            kind: Secret
            name: public-grafana-tls
      allowedRoutes:
        namespaces:
          selector:
            matchExpressions:
              - key: name
                operator: In
                values:
                  - infra-monitoring
