name: infra-network-cert-manager
description: Network infrastructure setup for homelab
version: 0.1.0
apiVersion: v2
type: application
appVersion: "1.0.0"
maintainers:
  - name: KarafrOrg
    email: karafra@karafra.net
keywords:
  - monitoring
  - prometheus
  - grafana
  - loki
  - homelab
