cert-manager:
  installCRDs: true
  crds:
    enabled: true
  prometheus:
    servicemonitor:
      enabled: true
      labels:
        metrics-collector: prometheus
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
      ephemeral-storage: 500Mi
    requests:
      cpu: 50m
      memory: 128Mi
      ephemeral-storage: 500Mi
  cainjector:
    resources:
      limits:
        cpu: 50m
        memory: 128Mi
        ephemeral-storage: 200Mi
      requests:
        cpu: 25m
        memory: 64Mi
        ephemeral-storage: 200Mi
  webhook:
    resources:
      limits:
        cpu: 50m
        memory: 128Mi
        ephemeral-storage: 200Mi
      requests:
        cpu: 25m
        memory: 64Mi
        ephemeral-storage: 200Mi
clusterIssuers:
  - email: mtoth575@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRefName: letsencrypt
    solversIngressClass: traefik
  - email: mtoth575@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRefName: letsencrypt-prod
    solversIngressClass: traefik
  - email: mtoth575@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRefName: letsencrypt-staging
    solversIngressClass: traefik
